title: More for Less
logo: /assets/img/profile.png
description: software developer by day, noob hacktheboxer by night, trying to retain what I learned here.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
